# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CNAME
# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://ysinghc.me'
baseurl: ''
title: 'ysinghc'
description: 'This is my new blog'
permalink: pretty
logo: "/assets/images/ysinghc.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "These are just my thoughts while I am coding or just life in general :)"
  
