# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://ysinghc.me'
baseurl: ''
title: 'ysinghc'
description: 'This is my new blog'
permalink: pretty
logo: "ysinghc.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: "Blogs"
    output: true
    description: "There isn't much going on here yet, but watch this spac"
